name: Java CI
on:  
  push:
    branches:
      - main
  pull_request:
jobs:
  unit-test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    name: Run unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install the dependencies & run the tests
        working-directory: ./
        run: mvn clean test
  linter:
    needs: unit-test
    runs-on: ubuntu-latest
    name: Run linter
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install the dependencies
        run: mvn clean install -DskipTests=true
      - name: Linter
        run: mvn spotless:apply
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply lint fixes
      
  
        
        
